<a href="https://colab.research.google.com/github/smkandel/Courses/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip install matplotlib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip install sklearn # scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Created wheel for sklearn: filename=sklearn-0.0.post5-py3-none-any.whl size=2950 sha256=cb3d2c6cfd4b31294d867b16f5de4097e19ed77e3e7493703a4bf3a197bd9971
  Stored in directory: /root/.cache/pip/wheels/38/1f/8d/4f812c590e074c1e928f5cec67bf5053b71f38e2648739403a
Successfully built sklearn


In [ ]:
import numpy as np

In [ ]:
lst1 = [1,2,3,4,5,6,7,8,9,10]
arr1 = np.array(lst1)
print(arr1)
print(type(arr1))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [ ]:
tup1 = ['p1','o2','i3','u4','y5','t6','r7','e8','w9','q10']
arr2 = np.array(tup1)
print(arr2)
print(type(arr2))

['p1' 'o2' 'i3' 'u4' 'y5' 't6' 'r7' 'e8' 'w9' 'q10']
<class 'numpy.ndarray'>


In [ ]:
set1 = {'p1','o2','i3','u4','y5','t6','r7','e8','w9','q10',True,False,1,2,3,4,5,6,7,8,9,10}
arr3 = np.array(set1)
print(arr3)
print(type(arr3))

{False, 'u4', 2, 3, True, 4, 5, 6, 7, 'e8', 8, 9, 10, 'i3', 'p1', 'w9', 't6', 'o2', 'r7', 'q10', 'y5'}
<class 'numpy.ndarray'>


In [ ]:
dict1 = {'p1':1,'o2':2,'i3':3,'u4':4,'y5':5,'t6':6,'r7':7,'e8':8,'w9':9,'q10':10}
arr4 = np.array(dict1)
print(arr4)
print(type(arr4))

{'p1': 1, 'o2': 2, 'i3': 3, 'u4': 4, 'y5': 5, 't6': 6, 'r7': 7, 'e8': 8, 'w9': 9, 'q10': 10}
<class 'numpy.ndarray'>


In [ ]:
str1 = 'Python Programming'
arr5 = np.array(str1)
print(arr5)
print(type(arr5))

Python Programming
<class 'numpy.ndarray'>


In [ ]:
lst1 = [10,20,30,40,50,60,70,80,90,100]
arr1 = np.array(lst1)
print(arr1)
print(type(arr1))
arr1

[ 10  20  30  40  50  60  70  80  90 100]
<class 'numpy.ndarray'>


array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
arr1.astype(float)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10, 100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [ ]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(100,0, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [ ]:
arr7 = np.arange(100,0, -10)
arr7, arr7.dtype, arr7.shape

(array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10]),
 dtype('int64'),
 (10,))

In [ ]:
lst2 = [[1,2,3],[4,5,6],[7,8,9]]
arr7_2d = np.array(lst2)
print(arr7_2d)
print(type(arr7_2d))
arr7_2d.dtype, arr7_2d.size, arr7_2d.ndim, arr7_2d.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


(dtype('int64'), 9, 2, (3, 3))

In [ ]:
lst3 = [
        [
            [1,2,3],[2,3,4],[3,4,5]
         ],
          [
              [4,5,6],[5,6,7],[6,7,8]
           ],
            [
                [7,8,9],[8,9,0],[9,0,1]
             ]
        ]

In [ ]:
arr8_3d = np.array(lst3)

In [ ]:
arr8_3d

array([[[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]],

       [[4, 5, 6],
        [5, 6, 7],
        [6, 7, 8]],

       [[7, 8, 9],
        [8, 9, 0],
        [9, 0, 1]]])

In [ ]:
arr8_3d.ndim

3

In [ ]:
arr8_3d.shape

(3, 3, 3)

In [ ]:
np.random.random(10)

array([0.56944356, 0.86078123, 0.80927569, 0.1434573 , 0.33913777,
       0.19072474, 0.86748173, 0.58593626, 0.38710305, 0.53477577])

In [ ]:
np.random.random(1000)

array([1.73718145e-01, 5.26876750e-01, 7.69568682e-01, 4.09202973e-01,
       7.39786397e-01, 1.73078537e-01, 9.52541375e-01, 6.97678290e-01,
       8.45057612e-01, 9.40828251e-01, 7.04507952e-02, 6.50810290e-01,
       7.75518621e-01, 3.20835524e-01, 4.96896452e-01, 6.24777176e-01,
       2.44596959e-01, 1.69910838e-01, 7.96427013e-02, 5.03191235e-01,
       3.25264788e-02, 9.57912781e-01, 8.49321476e-01, 3.22387296e-01,
       6.65654899e-01, 5.75803177e-01, 2.78664141e-01, 4.43494062e-01,
       7.59149344e-01, 6.58761795e-01, 3.35119750e-01, 6.16253262e-01,
       9.20531162e-01, 8.97799875e-02, 1.92522028e-02, 9.06529045e-01,
       8.26244336e-01, 2.09063016e-01, 4.65027044e-01, 7.53805276e-01,
       3.35819144e-01, 3.99940070e-01, 1.99250045e-02, 2.96020330e-02,
       7.65780402e-02, 3.62281396e-01, 3.73336025e-01, 5.84428107e-01,
       5.01694050e-01, 3.32907579e-01, 5.99466418e-01, 8.61745094e-01,
       8.81940680e-01, 9.80246617e-01, 4.05596151e-01, 4.85010931e-01,
      

In [ ]:
np.random.randint(0, 500, 5)

array([406, 373, 208, 365,  58])

In [ ]:
np.random.randint(-1000, -500, 5)

array([-859, -877, -728, -941, -585])

In [ ]:
np.random.randint(-500, -1,  25)

array([-405, -139, -491,  -40, -380, -125, -301, -151, -247, -351, -142,
       -397, -274, -335, -459, -272, -293, -454, -434,  -90,  -35, -289,
       -333, -458, -482])